### PR TITLE
Passes options all the way down in key CRUD fns

### PR DESCRIPTION
**Pull request by isaacsanders**
Specifically `insert!`, `update!`, and `delete!`.

This is terribly inconvenient to not be able to pass options down, especially when it may allow one to tune their use of the library better.

### CODE REVIEW

**Comment by isaacsanders** [comment]
I moved too fast. I didn't see the contributor guidelines.

**Comment by isaacsanders** [comment]
Is there a way that I can get the spirit of this change made without my going through the ceremony of becoming a committer?

**Comment by seancorfield** [comment]
Hi Isaac! Thanks for spotting the contributing guidelines. Unfortunately we can't disable Pull Requests on GitHub, even tho' we can (and have) disabled Issues. Anyone can create a JIRA account and create an enhancement request: http://dev.clojure.org/jira/browse/JDBC

If you'd like to create an issue there and refer back to this Pull Request with a link, then I'll take a look and see if I've missed any other places where options _could_ reasonably be passed through the call chain. I suspect when I implemented this I had reason to exclude certain options, but I have already made a couple of passes over the code to pass options in more places so this PR will act as a check list for me to review all the functions.

**Comment by isaacsanders** [comment]
Refer to: http://dev.clojure.org/jira/browse/JDBC-144

**Pull request closed without merging**
